-- Mingde VP Chamber commerce event reliability baseline v1.
-- Target: MySQL 5.7-8.0 / CRMEB v6.0.0.
-- These are append-oriented records: identity and request facts are immutable;
-- services may only advance leases, processing state, retries, and final results.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `ch_commerce_event_inbox` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '事件收件记录ID',
  `tenant_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户ID',
  `event_id` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '确定性商业事件SHA-256标识',
  `source` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '事件来源，不含用户信息',
  `event_type` varchar(48) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '稳定事件类型',
  `source_event_id` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '来源系统事件ID，不得包含PII',
  `schema_version` tinyint(3) UNSIGNED NOT NULL DEFAULT '1' COMMENT '事件载荷契约版本',
  `channel_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '非PII渠道上下文ID',
  `order_pk` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'CRMEB eb_store_order.id，非订单时为0',
  `order_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT 'CRMEB订单号/稳定商业单号',
  `business_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT '领域业务类型',
  `context_id` bigint(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT '领域业务上下文ID',
  `correlation_id` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT '跨服务关联ID',
  `payload_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '规范化脱敏载荷SHA-256',
  `payload_json` longtext NOT NULL COMMENT '最小化脱敏事件载荷JSON，严禁存储PII',
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'received' COMMENT 'received/processing/processed/failed/conflict',
  `attempt_count` smallint(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '消费尝试次数',
  `lease_token` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT '消费者租约令牌',
  `lease_expire_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '消费者租约到期时间',
  `next_retry_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '下次允许消费时间',
  `last_error_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT '最近错误码，不记录异常原文或PII',
  `occurred_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '来源事件发生时间',
  `received_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '首次接收时间',
  `processed_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '处理完成时间',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_commerce_event_id` (`event_id`) USING BTREE,
  UNIQUE KEY `uk_commerce_event_source` (`tenant_id`,`source`,`event_type`,`source_event_id`) USING BTREE,
  KEY `idx_commerce_event_work` (`tenant_id`,`status`,`next_retry_time`,`id`) USING BTREE,
  KEY `idx_commerce_event_order` (`tenant_id`,`order_pk`,`order_no`,`id`) USING BTREE,
  KEY `idx_commerce_event_business` (`tenant_id`,`business_type`,`context_id`,`id`) USING BTREE,
  KEY `idx_commerce_event_hash` (`tenant_id`,`payload_hash`) USING BTREE,
  KEY `idx_commerce_event_received` (`tenant_id`,`received_time`,`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='无PII商业事件幂等收件箱';

CREATE TABLE IF NOT EXISTS `ch_idempotency_record` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '幂等记录ID',
  `tenant_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户ID',
  `idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '租户内稳定幂等键',
  `operation` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '受保护操作标识',
  `request_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '规范化请求SHA-256，用于检测键冲突',
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'processing' COMMENT 'processing/succeeded/failed/unknown',
  `lease_token` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT '当前执行租约令牌',
  `lease_expire_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租约到期时间',
  `attempt_count` smallint(5) UNSIGNED NOT NULL DEFAULT '1' COMMENT '获取执行权次数',
  `result_http_status` smallint(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '可重放HTTP状态码，0为未完成',
  `result_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT '稳定业务结果码',
  `result_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT '规范化结果SHA-256',
  `result_json` longtext COMMENT '可重放最小结果JSON，不保存密钥或敏感原文',
  `completed_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '终态完成时间',
  `expire_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '记录保留截止时间，0为长期',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_idempotency_tenant_key` (`tenant_id`,`idempotency_key`) USING BTREE,
  KEY `idx_idempotency_lease` (`tenant_id`,`status`,`lease_expire_time`,`id`) USING BTREE,
  KEY `idx_idempotency_operation` (`tenant_id`,`operation`,`status`,`add_time`) USING BTREE,
  KEY `idx_idempotency_expire` (`tenant_id`,`expire_time`,`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='跨请求幂等租约与结果记录';

CREATE TABLE IF NOT EXISTS `ch_refund_attempt` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '退款尝试ID',
  `tenant_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户ID',
  `refund_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '租户内不可变退款业务号',
  `idempotency_record_id` bigint(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_idempotency_record.id',
  `commerce_event_id` bigint(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT '触发事件ch_commerce_event_inbox.id',
  `source_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '退款业务来源类型',
  `source_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '退款业务来源ID',
  `crmeb_order_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'CRMEB eb_store_order.id',
  `crmeb_order_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT 'CRMEB订单号快照',
  `crmeb_refund_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'CRMEB eb_store_order_refund.id',
  `provider` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'weixin_v2/weixin_v3/alipay/allinpay/balance/offline等',
  `provider_trade_no` varchar(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT '原支付渠道交易号',
  `provider_refund_no` varchar(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '提交渠道前生成并持久化的退款号',
  `provider_refund_id` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT '渠道返回的退款ID',
  `provider_status` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT '最近一次渠道原始状态码',
  `currency` char(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'CNY' COMMENT 'ISO 4217币种',
  `amount` decimal(16,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '本次退款金额',
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'requested' COMMENT 'requested/processing/succeeded/failed/unknown/manual',
  `request_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '规范化渠道退款请求SHA-256',
  `last_response_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT '最近渠道响应SHA-256，不保存敏感原文',
  `query_retry_count` smallint(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '渠道查询重试次数',
  `next_query_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '下次渠道查询时间',
  `last_query_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '最近渠道查询时间',
  `final_confirmed` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否已获得渠道或人工最终确认',
  `final_confirm_source` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT 'balance_transaction/provider_query_success/manual_finance_confirm',
  `final_confirm_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '最终确认时间',
  `failure_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT '稳定失败码，不记录敏感原文',
  `manual_operator_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '线下人工确认管理员ID',
  `manual_reference` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT '线下退款凭证对象键/非敏感引用',
  `request_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '首次发起时间',
  `processing_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '进入渠道处理时间',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_refund_attempt_no` (`tenant_id`,`refund_no`) USING BTREE,
  UNIQUE KEY `uk_refund_provider_no` (`tenant_id`,`provider`,`provider_refund_no`) USING BTREE,
  KEY `idx_refund_source` (`tenant_id`,`source_type`,`source_id`,`id`) USING BTREE,
  KEY `idx_refund_order` (`tenant_id`,`crmeb_order_id`,`status`,`id`) USING BTREE,
  KEY `idx_refund_query` (`tenant_id`,`status`,`next_query_time`,`id`) USING BTREE,
  KEY `idx_refund_provider_id` (`tenant_id`,`provider`,`provider_refund_id`) USING BTREE,
  KEY `idx_refund_final` (`tenant_id`,`final_confirmed`,`status`,`update_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='渠道退款尝试与最终确认记录';
