-- Mingde VP Chamber membership commerce facts v1.
-- Target: MySQL 5.7-8.0 / CRMEB v6.0.0.
-- Order and entitlement snapshots are immutable business facts. Runtime services
-- may advance lifecycle fields, but must never rewrite ownership or pricing facts.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `ch_membership_plan` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '会籍计划ID',
  `tenant_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户ID',
  `channel_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '渠道ID，必须显式指定',
  `plan_code` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '租户渠道内稳定计划编码',
  `name` varchar(80) NOT NULL DEFAULT '' COMMENT '计划展示名称',
  `tier` tinyint(1) UNSIGNED NOT NULL DEFAULT '3' COMMENT '会籍等级：3=L3，4=L4',
  `purchase_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否允许购买：0否，1是',
  `price` decimal(16,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '计划价格',
  `currency` char(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'CNY' COMMENT 'ISO 4217币种',
  `term_months` smallint(5) UNSIGNED NOT NULL DEFAULT '12' COMMENT '每次购买增加月数',
  `product_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'CRMEB eb_store_product.id',
  `product_attr_unique` varchar(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT 'CRMEB规格唯一值',
  `benefits_json` longtext NOT NULL COMMENT '权益配置JSON',
  `renewal_policy_json` longtext NOT NULL COMMENT '续费规则JSON',
  `upgrade_policy_json` longtext NOT NULL COMMENT '升级规则JSON',
  `refund_policy_json` longtext NOT NULL COMMENT '退款规则JSON',
  `config_version` int(10) UNSIGNED NOT NULL DEFAULT '1' COMMENT '配置版本',
  `status` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '状态：0草稿，1启用，2停用，3归档',
  `effective_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '配置生效时间',
  `end_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '配置失效时间，0为未计划',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_membership_plan_code` (`tenant_id`,`channel_id`,`plan_code`) USING BTREE,
  UNIQUE KEY `uk_membership_plan_tier` (`tenant_id`,`channel_id`,`tier`) USING BTREE,
  KEY `idx_membership_plan_sale` (`tenant_id`,`channel_id`,`status`,`purchase_enabled`,`tier`) USING BTREE,
  KEY `idx_membership_plan_product` (`tenant_id`,`channel_id`,`product_id`,`product_attr_unique`,`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='租户渠道会籍计划';

CREATE TABLE IF NOT EXISTS `ch_order_context` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '领域订单上下文ID',
  `tenant_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户ID',
  `channel_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '渠道ID',
  `member_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_tenant_member.id',
  `uid` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'CRMEB eb_user.uid',
  `context_no` char(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '租户内上下文编号',
  `order_pk` int(10) UNSIGNED NULL COMMENT 'CRMEB eb_store_order.id，订单绑定前为NULL',
  `order_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT 'CRMEB订单号，订单绑定前为NULL',
  `business_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '业务类型：membership/event/appointment等',
  `business_id` bigint(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT '领域业务ID，会籍为plan_id',
  `currency` char(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'CNY' COMMENT 'ISO 4217币种',
  `list_amount` decimal(16,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '标价金额快照',
  `payable_amount` decimal(16,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '应付金额快照',
  `paid_amount` decimal(16,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '可信已付累计金额',
  `refunded_amount` decimal(16,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '可信已退累计金额',
  `integral_amount` decimal(16,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '积分金额快照',
  `price_snapshot_json` longtext NOT NULL COMMENT '价格快照JSON',
  `entitlement_snapshot_json` longtext NOT NULL COMMENT '权益快照JSON',
  `refund_policy_snapshot_json` longtext NOT NULL COMMENT '退款政策快照JSON',
  `settlement_snapshot_json` longtext NOT NULL COMMENT '分账政策快照JSON',
  `pay_status` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '支付：0待支付，1已完成，2已取消，3已关闭',
  `completion_kind` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'pending' COMMENT 'pending/paid/zero_amount',
  `refund_status` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '退款：0无，1已申请，2处理中，3部分完成，4完成，5取消，6失败',
  `paid_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '可信支付完成时间',
  `version` int(10) UNSIGNED NOT NULL DEFAULT '1' COMMENT '乐观锁版本',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_order_context_no` (`tenant_id`,`context_no`) USING BTREE,
  UNIQUE KEY `uk_order_context_order_pk` (`order_pk`) USING BTREE,
  UNIQUE KEY `uk_order_context_order_no` (`tenant_id`,`order_no`,`uid`) USING BTREE,
  KEY `idx_order_context_member` (`tenant_id`,`member_id`,`pay_status`,`add_time`) USING BTREE,
  KEY `idx_order_context_business` (`tenant_id`,`business_type`,`business_id`,`pay_status`) USING BTREE,
  KEY `idx_order_context_refund` (`tenant_id`,`refund_status`,`update_time`) USING BTREE,
  KEY `idx_order_context_channel` (`tenant_id`,`channel_id`,`pay_status`,`add_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CRMEB订单领域上下文与不可变快照';

CREATE TABLE IF NOT EXISTS `ch_membership_term` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '会籍期限ID',
  `tenant_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户ID',
  `channel_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '购买渠道ID',
  `member_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_tenant_member.id',
  `uid` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'CRMEB eb_user.uid',
  `term_no` char(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '租户内会籍期限编号',
  `plan_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_membership_plan.id快照来源',
  `plan_code` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '计划编码快照',
  `tier` tinyint(1) UNSIGNED NOT NULL DEFAULT '3' COMMENT '会籍等级：3=L3，4=L4',
  `order_context_id` bigint(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_order_context.id',
  `order_pk` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'CRMEB eb_store_order.id',
  `order_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT 'CRMEB订单号快照',
  `source_type` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'purchase' COMMENT 'purchase/admin/grant',
  `currency` char(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'CNY' COMMENT 'ISO 4217币种',
  `paid_amount` decimal(16,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '本期限实付金额',
  `refunded_amount` decimal(16,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '本期限可信已退金额',
  `original_start_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '授予时原始开始时间',
  `original_end_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '授予时原始结束时间',
  `effective_start_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '当前有效开始时间，含',
  `effective_end_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '当前有效结束时间，不含',
  `state` tinyint(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '事实状态：1已授予，2已撤销，3已全额退款',
  `grant_event_id` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '授予来源商业事件ID',
  `plan_snapshot_json` longtext NOT NULL COMMENT '计划快照JSON',
  `benefits_snapshot_json` longtext NOT NULL COMMENT '权益快照JSON',
  `refund_policy_snapshot_json` longtext NOT NULL COMMENT '退款政策快照JSON',
  `version` int(10) UNSIGNED NOT NULL DEFAULT '1' COMMENT '乐观锁版本',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_membership_term_no` (`tenant_id`,`term_no`) USING BTREE,
  UNIQUE KEY `uk_membership_term_context` (`tenant_id`,`order_context_id`) USING BTREE,
  UNIQUE KEY `uk_membership_term_grant_event` (`tenant_id`,`grant_event_id`) USING BTREE,
  KEY `idx_membership_term_member` (`tenant_id`,`member_id`,`state`,`tier`,`effective_end_time`) USING BTREE,
  KEY `idx_membership_term_expiry` (`tenant_id`,`state`,`effective_end_time`,`id`) USING BTREE,
  KEY `idx_membership_term_order` (`tenant_id`,`order_pk`,`order_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='按支付订单追加的会籍期限事实';

CREATE TABLE IF NOT EXISTS `ch_membership_term_effect` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '会籍期限变更效果ID',
  `tenant_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户ID',
  `term_id` bigint(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_membership_term.id',
  `order_context_id` bigint(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_order_context.id',
  `effect_key` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '稳定幂等键SHA-256',
  `effect_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '规范化效果载荷SHA-256',
  `event_id` char(64) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '来源商业事件ID，人工操作可为NULL',
  `completion_id` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '退款完成证据ID，非退款可为NULL',
  `effect_type` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'grant/full_refund/adjustment等',
  `refund_delta` decimal(16,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '本次可信退款增量',
  `before_state` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '变更前事实状态，0为无记录',
  `after_state` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '变更后事实状态',
  `before_end_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '变更前结束时间',
  `after_end_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '变更后结束时间',
  `reason_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT '稳定原因码',
  `operator_type` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '0系统，1用户，2管理员',
  `operator_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '操作方ID，系统为0',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '发生时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_membership_effect_key` (`tenant_id`,`effect_key`) USING BTREE,
  UNIQUE KEY `uk_membership_effect_completion` (`tenant_id`,`term_id`,`completion_id`) USING BTREE,
  KEY `idx_membership_effect_term` (`tenant_id`,`term_id`,`id`) USING BTREE,
  KEY `idx_membership_effect_context` (`tenant_id`,`order_context_id`,`id`) USING BTREE,
  KEY `idx_membership_effect_event` (`tenant_id`,`event_id`,`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='追加式会籍授予退款与人工调整效果';
