SELECT COLUMN_NAME FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA='crmeb' AND TABLE_NAME='ch_settlement_detail'
AND COLUMN_NAME IN ('claim_token','claim_expire_time','next_retry_time');
SELECT COLUMN_NAME FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA='crmeb' AND TABLE_NAME='ch_payout_record'
AND COLUMN_NAME IN ('request_payload_hash','query_count','last_query_time');
SELECT INDEX_NAME FROM information_schema.STATISTICS
WHERE TABLE_SCHEMA='crmeb' AND TABLE_NAME='ch_settlement_detail'
AND INDEX_NAME IN ('idx_due','idx_claim');
