-- Mingde VP Chamber core schema v1
-- Target: MySQL 5.7-8.0 / CRMEB v6.0.0
-- This file is intentionally idempotent for local bootstrap and CI smoke tests.
-- DDL statements auto-commit in MySQL; deploy this migration before application code.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `ch_tenant` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '租户ID',
  `name` varchar(80) NOT NULL DEFAULT '' COMMENT '租户名称',
  `slug` varchar(64) NOT NULL COMMENT '稳定租户标识，不允许复用',
  `display_name` varchar(80) NOT NULL DEFAULT '' COMMENT '前台展示名称',
  `contact_name` varchar(40) NOT NULL DEFAULT '' COMMENT '业务联系人',
  `contact_phone` varchar(20) NOT NULL DEFAULT '' COMMENT '业务联系电话',
  `status` tinyint(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态：0禁用，1启用',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  `is_del` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '软删除：0否，1是',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_slug` (`slug`) USING BTREE,
  KEY `idx_tenant_status` (`status`,`is_del`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商会租户';

CREATE TABLE IF NOT EXISTS `ch_channel` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '渠道/运营组织ID',
  `tenant_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户ID',
  `name` varchar(80) NOT NULL DEFAULT '' COMMENT '渠道/运营组织名称',
  `code` varchar(64) NOT NULL COMMENT '租户内唯一渠道编码',
  `entry_key` char(32) NOT NULL COMMENT '签名入口使用的非敏感随机标识',
  `status` tinyint(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态：0禁用，1启用',
  `sort` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '排序',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  `is_del` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '软删除：0否，1是',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_channel_tenant_code` (`tenant_id`,`code`) USING BTREE,
  UNIQUE KEY `uk_channel_entry_key` (`entry_key`) USING BTREE,
  KEY `idx_channel_tenant_status` (`tenant_id`,`status`,`is_del`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='租户渠道与运营组织';

CREATE TABLE IF NOT EXISTS `ch_tenant_member` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '租户会员ID',
  `tenant_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户ID',
  `uid` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'CRMEB eb_user.uid',
  `first_channel_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '首次归因渠道ID',
  `current_channel_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '当前服务渠道ID',
  `referrer_uid` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户内直接推荐人uid',
  `tier` tinyint(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '当前会籍等级：1=L1，2=L2，3=L3，4=L4',
  `verification_status` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '毕业生认证：0未申请，1待审，2通过，3退回，4拒绝，5撤销',
  `primary_role_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '主展示人物角色ID',
  `status` tinyint(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '会员状态：0禁用，1正常，2退出',
  `join_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '加入租户时间',
  `certified_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'L2认证通过时间',
  `tier_expire_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '当前付费会籍到期时间，0为无',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  `is_del` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '软删除：0否，1是',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_member_uid` (`tenant_id`,`uid`) USING BTREE,
  KEY `idx_member_tenant_channel` (`tenant_id`,`current_channel_id`,`status`,`is_del`) USING BTREE,
  KEY `idx_member_tenant_tier` (`tenant_id`,`tier`,`verification_status`,`status`) USING BTREE,
  KEY `idx_member_referrer` (`tenant_id`,`referrer_uid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='租户会员身份';

CREATE TABLE IF NOT EXISTS `ch_member_profile` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '会员资料ID',
  `tenant_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户ID',
  `member_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_tenant_member.id',
  `uid` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'CRMEB eb_user.uid',
  `real_name` varchar(40) NOT NULL DEFAULT '' COMMENT '租户内展示姓名',
  `class_name` varchar(80) NOT NULL DEFAULT '' COMMENT '毕业班级/期次',
  `graduation_year` smallint(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '毕业年份',
  `industry` varchar(80) NOT NULL DEFAULT '' COMMENT '行业',
  `company_name` varchar(120) NOT NULL DEFAULT '' COMMENT '公司/机构',
  `job_title` varchar(80) NOT NULL DEFAULT '' COMMENT '职位',
  `province` varchar(40) NOT NULL DEFAULT '' COMMENT '省份',
  `city` varchar(40) NOT NULL DEFAULT '' COMMENT '城市',
  `bio` varchar(1000) NOT NULL DEFAULT '' COMMENT '个人简介',
  `expertise_json` text COMMENT '擅长领域JSON数组',
  `privacy_json` text COMMENT '字段可见性JSON对象',
  `profile_status` tinyint(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '资料状态：0隐藏，1展示，2待完善',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  `is_del` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '软删除：0否，1是',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_profile_tenant_member` (`tenant_id`,`member_id`) USING BTREE,
  UNIQUE KEY `uk_profile_tenant_uid` (`tenant_id`,`uid`) USING BTREE,
  KEY `idx_profile_directory` (`tenant_id`,`profile_status`,`is_del`,`graduation_year`) USING BTREE,
  KEY `idx_profile_city` (`tenant_id`,`city`,`is_del`) USING BTREE,
  KEY `idx_profile_industry` (`tenant_id`,`industry`,`is_del`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='租户会员扩展资料';

CREATE TABLE IF NOT EXISTS `ch_graduate_verification` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '毕业生认证申请ID',
  `tenant_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户ID',
  `member_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_tenant_member.id',
  `uid` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '申请人eb_user.uid',
  `channel_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '申请渠道ID',
  `apply_no` char(32) NOT NULL COMMENT '租户内唯一申请编号',
  `class_name` varchar(80) NOT NULL DEFAULT '' COMMENT '毕业班级/期次快照',
  `graduation_year` smallint(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '毕业年份快照',
  `proof_json` text COMMENT '证明材料对象键JSON数组，不存公开URL',
  `status` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '状态：0草稿，1待审，2通过，3退回，4拒绝，5撤销',
  `reviewer_admin_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '最近审核管理员ID',
  `review_note` varchar(500) NOT NULL DEFAULT '' COMMENT '最近审核意见',
  `submit_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '提交时间',
  `review_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '最近审核时间',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_verification_apply_no` (`tenant_id`,`apply_no`) USING BTREE,
  KEY `idx_verification_member` (`tenant_id`,`member_id`,`status`) USING BTREE,
  KEY `idx_verification_review` (`tenant_id`,`status`,`submit_time`) USING BTREE,
  KEY `idx_verification_channel` (`tenant_id`,`channel_id`,`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='毕业生认证申请';

CREATE TABLE IF NOT EXISTS `ch_audit_record` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '审计记录ID',
  `tenant_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户ID',
  `business_type` varchar(32) NOT NULL DEFAULT '' COMMENT '业务类型：graduate_verification/role_application等',
  `business_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '业务记录ID',
  `action` varchar(32) NOT NULL DEFAULT '' COMMENT '动作：submit/approve/return/reject/revoke等',
  `from_status` tinyint(3) NOT NULL DEFAULT '0' COMMENT '变更前状态',
  `to_status` tinyint(3) NOT NULL DEFAULT '0' COMMENT '变更后状态',
  `operator_type` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '操作方：0系统，1用户，2管理员',
  `operator_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '操作方uid/admin_id，系统为0',
  `opinion` varchar(500) NOT NULL DEFAULT '' COMMENT '审核意见/操作原因',
  `extra_json` text COMMENT '必要的非敏感审计上下文JSON',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '发生时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_audit_business` (`tenant_id`,`business_type`,`business_id`,`id`) USING BTREE,
  KEY `idx_audit_operator` (`tenant_id`,`operator_type`,`operator_id`,`add_time`) USING BTREE,
  KEY `idx_audit_time` (`tenant_id`,`add_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='不可变业务审核审计记录';

CREATE TABLE IF NOT EXISTS `ch_persona_role` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '人物角色ID',
  `tenant_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户ID',
  `code` varchar(32) NOT NULL COMMENT '稳定角色编码',
  `name` varchar(40) NOT NULL DEFAULT '' COMMENT '角色名称',
  `description` varchar(500) NOT NULL DEFAULT '' COMMENT '角色说明',
  `application_required` tinyint(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '是否需要申请审核',
  `materials_schema_json` text COMMENT '申请材料字段定义JSON',
  `profile_template` varchar(32) NOT NULL DEFAULT 'member' COMMENT '主页模板标识',
  `status` tinyint(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态：0停用，1启用',
  `sort` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '排序',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  `is_del` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '软删除：0否，1是',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_persona_role_code` (`tenant_id`,`code`) USING BTREE,
  KEY `idx_persona_role_status` (`tenant_id`,`status`,`is_del`,`sort`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='租户人物角色配置';

CREATE TABLE IF NOT EXISTS `ch_role_application` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '人物角色申请ID',
  `tenant_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户ID',
  `member_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_tenant_member.id',
  `uid` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '申请人eb_user.uid',
  `role_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_persona_role.id',
  `apply_no` char(32) NOT NULL COMMENT '租户内唯一申请编号',
  `materials_json` text COMMENT '申请材料对象键及表单值JSON',
  `status` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '状态：0草稿，1待审，2通过，3退回，4拒绝，5撤销',
  `reviewer_admin_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '最近审核管理员ID',
  `review_note` varchar(500) NOT NULL DEFAULT '' COMMENT '最近审核意见',
  `valid_until` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '资质有效期，0为长期',
  `submit_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '提交时间',
  `review_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '最近审核时间',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_role_application_no` (`tenant_id`,`apply_no`) USING BTREE,
  KEY `idx_role_application_member` (`tenant_id`,`member_id`,`role_id`,`status`) USING BTREE,
  KEY `idx_role_application_review` (`tenant_id`,`status`,`submit_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='人物角色申请';

CREATE TABLE IF NOT EXISTS `ch_member_role` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '会员人物角色关系ID',
  `tenant_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户ID',
  `member_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_tenant_member.id',
  `uid` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '会员eb_user.uid',
  `role_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_persona_role.id',
  `is_primary` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否主展示角色：0否，1是',
  `grant_source` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '授予来源：0系统，1申请，2邀请，3管理员',
  `source_application_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '来源角色申请ID',
  `status` tinyint(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态：0已撤销，1有效，2已过期',
  `effective_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '生效时间',
  `expire_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '到期时间，0为长期',
  `revoke_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '撤销时间',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_member_role` (`tenant_id`,`member_id`,`role_id`) USING BTREE,
  KEY `idx_member_role_uid` (`tenant_id`,`uid`,`status`) USING BTREE,
  KEY `idx_member_role_role` (`tenant_id`,`role_id`,`status`,`expire_time`) USING BTREE,
  KEY `idx_member_role_primary` (`tenant_id`,`member_id`,`is_primary`,`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会员人物角色关系';

CREATE TABLE IF NOT EXISTS `ch_event` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '活动ID',
  `tenant_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户ID',
  `channel_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '主办渠道ID',
  `event_no` char(32) NOT NULL COMMENT '租户内唯一活动编号',
  `event_type` varchar(32) NOT NULL DEFAULT '' COMMENT '活动类型：growth/industry/public_welfare',
  `title` varchar(160) NOT NULL DEFAULT '' COMMENT '活动标题',
  `cover_image` varchar(255) NOT NULL DEFAULT '' COMMENT '封面对象键/受控资源路径',
  `summary` varchar(500) NOT NULL DEFAULT '' COMMENT '活动摘要',
  `detail` longtext COMMENT '活动详情',
  `start_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '开始时间',
  `end_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '结束时间',
  `signup_start_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '报名开始时间',
  `signup_end_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '报名结束时间',
  `location_name` varchar(120) NOT NULL DEFAULT '' COMMENT '地点名称',
  `address` varchar(255) NOT NULL DEFAULT '' COMMENT '详细地址',
  `longitude` decimal(10,6) NOT NULL DEFAULT '0.000000' COMMENT '经度',
  `latitude` decimal(10,6) NOT NULL DEFAULT '0.000000' COMMENT '纬度',
  `min_tier` tinyint(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '最低会籍等级L1-L4',
  `eligibility_json` text COMMENT '角色/渠道/积分等资格规则JSON快照',
  `status` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '状态：0草稿，1已发布，2报名截止，3已结束，4已取消',
  `created_admin_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建管理员ID',
  `publish_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '发布时间',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  `is_del` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '软删除：0否，1是',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_event_no` (`tenant_id`,`event_no`) USING BTREE,
  KEY `idx_event_list` (`tenant_id`,`status`,`is_del`,`start_time`) USING BTREE,
  KEY `idx_event_channel` (`tenant_id`,`channel_id`,`status`,`start_time`) USING BTREE,
  KEY `idx_event_type` (`tenant_id`,`event_type`,`status`,`start_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商会线下/线上活动';

CREATE TABLE IF NOT EXISTS `ch_event_ticket` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '活动票种ID',
  `tenant_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户ID',
  `event_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_event.id',
  `name` varchar(80) NOT NULL DEFAULT '' COMMENT '票种名称',
  `price` decimal(12,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '现金价格',
  `integral_price` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '所需租户积分',
  `product_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '关联eb_store_product.id，免费票可为0',
  `product_attr_unique` varchar(20) NOT NULL DEFAULT '' COMMENT '关联CRMEB规格唯一值',
  `capacity` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '名额，0为不限',
  `reserved_count` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '待支付占用名额缓存',
  `paid_count` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '已确认报名名额缓存',
  `min_tier` tinyint(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '最低会籍等级L1-L4',
  `eligibility_json` text COMMENT '票种资格规则JSON快照',
  `sale_start_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '开售时间',
  `sale_end_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '停售时间',
  `status` tinyint(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态：0停售，1在售',
  `sort` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '排序',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  `is_del` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '软删除：0否，1是',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_ticket_event` (`tenant_id`,`event_id`,`status`,`is_del`,`sort`) USING BTREE,
  KEY `idx_ticket_product` (`tenant_id`,`product_id`,`product_attr_unique`) USING BTREE,
  KEY `idx_ticket_sale` (`tenant_id`,`status`,`sale_start_time`,`sale_end_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='活动票种';

CREATE TABLE IF NOT EXISTS `ch_event_registration` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '活动报名ID',
  `tenant_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户ID',
  `event_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_event.id',
  `ticket_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_event_ticket.id',
  `member_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_tenant_member.id',
  `uid` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '报名人eb_user.uid',
  `registration_no` char(32) NOT NULL COMMENT '租户内唯一报名编号',
  `order_pk` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'eb_store_order.id',
  `order_no` varchar(32) NOT NULL DEFAULT '' COMMENT 'eb_store_order.order_id',
  `amount` decimal(12,2) UNSIGNED NOT NULL DEFAULT '0.00' COMMENT '报名现金金额快照',
  `integral_amount` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '报名积分金额快照',
  `status` tinyint(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '状态：0待支付，1已报名，2已取消，3已退款，4候补，5已完成',
  `reserve_expire_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '待支付名额释放时间',
  `paid_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '确认报名时间',
  `cancel_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '取消时间',
  `refund_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '退款完成时间',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_registration_no` (`tenant_id`,`registration_no`) USING BTREE,
  UNIQUE KEY `uk_registration_member` (`tenant_id`,`event_id`,`uid`) USING BTREE,
  KEY `idx_registration_ticket` (`tenant_id`,`ticket_id`,`status`,`reserve_expire_time`) USING BTREE,
  KEY `idx_registration_member` (`tenant_id`,`member_id`,`status`,`add_time`) USING BTREE,
  KEY `idx_registration_order` (`tenant_id`,`order_pk`,`order_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='活动报名及名额占用';

CREATE TABLE IF NOT EXISTS `ch_event_checkin` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '活动签到ID',
  `tenant_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '租户ID',
  `event_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_event.id',
  `registration_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_event_registration.id',
  `member_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ch_tenant_member.id',
  `uid` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '签到会员eb_user.uid',
  `checkin_type` tinyint(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '签到方式：1扫码，2人工补签',
  `token_digest` char(64) NOT NULL DEFAULT '' COMMENT '签到令牌SHA-256摘要，不保存原令牌',
  `operator_admin_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '补签/核销管理员ID',
  `reason` varchar(500) NOT NULL DEFAULT '' COMMENT '人工补签原因',
  `checked_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '签到时间',
  `add_time` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_checkin_registration` (`tenant_id`,`registration_id`) USING BTREE,
  UNIQUE KEY `uk_checkin_member` (`tenant_id`,`event_id`,`uid`) USING BTREE,
  KEY `idx_checkin_event_time` (`tenant_id`,`event_id`,`checked_time`) USING BTREE,
  KEY `idx_checkin_operator` (`tenant_id`,`operator_admin_id`,`checked_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='活动签到记录';
